version: '3.8'

services:
  svelte-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    environment:
      VITE_API_URL: "http://localhost:8080"
    volumes:
      - .:/app 
      - /app/node_modules 
    stdin_open: true
    tty: true
